Todo/Models/ErrorViewModel.cs
using System;

namespace Todo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Todo/Models/ManageUsersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace Todo.Models
{
    public class ManageUsersViewModel
    {
        public IdentityUser[] Admins { get; set; }
        public IdentityUser[] Users { get; set; }
    }
}

Todo/Models/TodoItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;

namespace Todo.Models
{
    public class TodoItem
    {
        public Guid Id { get; set; }

        [Required]
        public string Title { get; set; }

        [DataType(DataType.Date)]
        public DateTimeOffset? DueAt { get; set; }

        public bool Completed { get; set; }

        public string UserId{ get; set; }

    }
}

Todo/Models/TodoItemViewmodel.cs
namespace Todo.Models
{
    public class TodoItemViewmodel
    {
        public TodoItem[] Items { get; set;}
    }
}

Todo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Todo.Models;

namespace Todo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Todo/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Todo.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Todo.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<IdentityUser> m_userManager;
        private readonly RoleManager<IdentityRole> m_roleManager;

        public ManageUsersController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            m_userManager = userManager;
            m_roleManager = roleManager;
        }  
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var admins = (await m_userManager.GetUsersInRoleAsync("Administrator")).ToArray();
            var users = await m_userManager.Users.ToArrayAsync();
            var model = new ManageUsersViewModel()
            {
                Admins = admins,
                Users = users
            };

            return View(model);
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = m_userManager.Users.FirstOrDefault(x => x.Id == id);

            var res = await m_userManager.DeleteAsync(user);

            if (!res.Succeeded) return BadRequest("Could not delete user");

            return RedirectToAction("Index");
        }
    }
}

Todo/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Todo.Models;
using Todo.Services;

namespace Todo.Controllers
{
    [Authorize]
    public class TodoController : Controller
    {
        private readonly ITodoItemService m_itemService;
        private readonly UserManager<IdentityUser> m_userManager;

        public TodoController(ITodoItemService itemService, UserManager<IdentityUser> userManager)
        {
            m_itemService = itemService;
            m_userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await m_userManager.GetUserAsync(User);

            var items = await m_itemService.GetIncompleteItemsAsync(user);
            var model = new TodoItemViewmodel
            {
                Items = items
            };

            return View(model);
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItem(TodoItem item)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var user = await m_userManager.GetUserAsync(User);
            var res = await m_itemService.AddItemAsync(item, user);

            if (!res) return BadRequest("Could not add item");

            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MarkDone(Guid id)
        {
            if (id == Guid.Empty)
            {
                return RedirectToAction("Index");
            }
            var user = await m_userManager.GetUserAsync(User);
            var res = await m_itemService.MarkDoneAsync(id, user);

            if (!res)
            {
                return BadRequest("Could not mark item as done");
            }

            return RedirectToAction("Index");
        }
    }
}

Todo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Todo/Views/ManageUsers/Index.cshtml
@model ManageUsersViewModel

@{
    ViewData["Title"] = "Manage Users";
}

<h2>@ViewData["Title"]</h2>

<h3>Administrators</h3>

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Email</td>
        </tr>
    </thead>

    @foreach (var users in Model.Admins)
    {
        <tr>
            <td>@users.Id</td>
            <td>@users.Email</td>
        </tr>
    }
</table>

<h3>Users</h3>

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Email</td>
            <td>Delete User</td>
        </tr>
    </thead>

    @foreach (var users in Model.Users)
    {
        <tr>
            <td>@users.Id</td>
            <td>@users.Email</td>
            <td>
                <form asp-action="DeleteUser" method="post">
                    <input type="hidden" name="id" value="@users.Id" />
                    <button type="submit" class="ui-button">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

Todo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Todo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Todo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Todo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Todo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
        <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Todo/Views/Todo/AddItemPartial.cshtml
@model TodoItem


<form asp-action="AddItem" method="post">

    <label asp-for="Title"> Add a new Item:</label>
    <input asp-for="Title" />
    <label asp-for="DueAt"> Deadline:</label>
    <input type="text" asp-for="DueAt" id="datepicker"/>
    <button type="submit">Add</button>
</form>

Todo/Views/Todo/Index.cshtml
@model TodoItemViewmodel
@using Humanizer

@{
    ViewData["Title"] = "Manage your todo List";
}

@section Scripts{
    <script type="text/javascript">
        $(function() {
            $("#datepicker").datepicker({dateFormat: "dd/mm/yy"});
        });
    </script>
}

<div class="card todo-panel">
    <div class="card-header">@ViewData["Title"]</div>

    <table class="table table-hover">
        <thead>
            <tr>
                <td>&#x2714</td>
                <td>Item</td>
                <td>Due</td>
            </tr>
        </thead>

        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    <form asp-action="MarkDone" method="post">
                        <input type="checkbox" class="done-checkbox" />
                        <input type="hidden" name="id" value="@item.Id"/>
                    </form>
                </td>
                <td>@item.Title</td>
                <td>@item.DueAt.Humanize()</td>
            </tr>
        }
    </table>
    <div class="card-footer form-group">
        @await Html.PartialAsync("AddItemPartial", new TodoItem())
    </div>
</div>